/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan;

import java.text.DecimalFormat;

/**
 *
 * @author albi mudakar
 */
public class pomBensinGUI extends javax.swing.JFrame {

    /**
     * Creates new form pomBensinGUI
     */
    public pomBensinGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        konversiPertamaxButton21552011235 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pertamaxTextField21552011235 = new javax.swing.JTextField();
        pertaliteTextField21552011235 = new javax.swing.JTextField();
        inputTextField21552011235 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pertamaxLabel21552011235 = new javax.swing.JLabel();
        pertaliteLabel21552011235 = new javax.swing.JLabel();
        dexliteLabel21552011235 = new javax.swing.JLabel();
        dexliteTextField21552011235 = new javax.swing.JTextField();
        inputUang = new javax.swing.JLabel();
        konversiPertaliteButton21552011235 = new javax.swing.JButton();
        konversiDexliteButton21552011235 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        konversiPertamaxButton21552011235.setBackground(new java.awt.Color(255, 255, 255));
        konversiPertamaxButton21552011235.setForeground(new java.awt.Color(0, 153, 153));
        konversiPertamaxButton21552011235.setText("konversi");
        konversiPertamaxButton21552011235.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                konversiPertamaxButton21552011235MouseClicked(evt);
            }
        });
        konversiPertamaxButton21552011235.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konversiPertamaxButton21552011235ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel1.setText("PROGRAM POMBENSIN");

        pertamaxTextField21552011235.setBackground(new java.awt.Color(255, 204, 102));
        pertamaxTextField21552011235.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pertamaxTextField21552011235ActionPerformed(evt);
            }
        });

        pertaliteTextField21552011235.setBackground(new java.awt.Color(255, 204, 102));
        pertaliteTextField21552011235.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pertaliteTextField21552011235ActionPerformed(evt);
            }
        });

        inputTextField21552011235.setBackground(new java.awt.Color(102, 102, 255));
        inputTextField21552011235.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTextField21552011235ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel3.setText("ALBI");

        pertamaxLabel21552011235.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pertamaxLabel21552011235.setText("Pertamax");

        pertaliteLabel21552011235.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pertaliteLabel21552011235.setText("Pertalite");

        dexliteLabel21552011235.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dexliteLabel21552011235.setText("Dexlite");

        dexliteTextField21552011235.setBackground(new java.awt.Color(255, 204, 102));
        dexliteTextField21552011235.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dexliteTextField21552011235ActionPerformed(evt);
            }
        });

        inputUang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        inputUang.setText("Input uang");

        konversiPertaliteButton21552011235.setBackground(new java.awt.Color(255, 255, 255));
        konversiPertaliteButton21552011235.setForeground(new java.awt.Color(0, 153, 153));
        konversiPertaliteButton21552011235.setText("konversi");
        konversiPertaliteButton21552011235.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konversiPertaliteButton21552011235ActionPerformed(evt);
            }
        });

        konversiDexliteButton21552011235.setBackground(new java.awt.Color(255, 255, 255));
        konversiDexliteButton21552011235.setForeground(new java.awt.Color(0, 153, 153));
        konversiDexliteButton21552011235.setText("konversi");
        konversiDexliteButton21552011235.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konversiDexliteButton21552011235ActionPerformed(evt);
            }
        });

        jLabel2.setText("9.400 / Liter");

        jLabel4.setText("7.650 / Liter");

        jLabel5.setText("12.950 / Liter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputTextField21552011235, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(inputUang)
                        .addGap(250, 250, 250))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pertamaxTextField21552011235, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pertamaxLabel21552011235)
                    .addComponent(konversiPertamaxButton21552011235)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pertaliteLabel21552011235)
                    .addComponent(pertaliteTextField21552011235, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(konversiPertaliteButton21552011235)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dexliteTextField21552011235, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dexliteLabel21552011235)
                    .addComponent(konversiDexliteButton21552011235)
                    .addComponent(jLabel5))
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputUang, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTextField21552011235, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pertamaxLabel21552011235)
                    .addComponent(pertaliteLabel21552011235)
                    .addComponent(dexliteLabel21552011235))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pertamaxTextField21552011235, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pertaliteTextField21552011235, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dexliteTextField21552011235, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(konversiPertaliteButton21552011235)
                    .addComponent(konversiPertamaxButton21552011235)
                    .addComponent(konversiDexliteButton21552011235))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void konversiPertamaxButton21552011235ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konversiPertamaxButton21552011235ActionPerformed
        double inputUang = Double.parseDouble(inputTextField21552011235.getText());
        double pertamax = inputUang / 9400;
        DecimalFormat df = new DecimalFormat("#,###.##");
        pertamaxTextField21552011235.setText("   " + df.format(pertamax)+ " Liter");
    }//GEN-LAST:event_konversiPertamaxButton21552011235ActionPerformed

    private void inputTextField21552011235ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTextField21552011235ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTextField21552011235ActionPerformed

    private void pertamaxTextField21552011235ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pertamaxTextField21552011235ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pertamaxTextField21552011235ActionPerformed

    private void dexliteTextField21552011235ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dexliteTextField21552011235ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dexliteTextField21552011235ActionPerformed

    private void pertaliteTextField21552011235ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pertaliteTextField21552011235ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pertaliteTextField21552011235ActionPerformed

    private void konversiPertaliteButton21552011235ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konversiPertaliteButton21552011235ActionPerformed
        double inputUang = Double.parseDouble(inputTextField21552011235.getText());
        double pertalite = inputUang / 7650;
        DecimalFormat df = new DecimalFormat("#,###.##");
        pertaliteTextField21552011235.setText("   " + df.format(pertalite)+ " Liter");
    }//GEN-LAST:event_konversiPertaliteButton21552011235ActionPerformed

    private void konversiDexliteButton21552011235ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konversiDexliteButton21552011235ActionPerformed
        double inputUang = Double.parseDouble(inputTextField21552011235.getText());
        double pertalite = inputUang / 12950;
        DecimalFormat df = new DecimalFormat("#,###.##");
        dexliteTextField21552011235.setText("   " + df.format(pertalite)+ " Liter");
    }//GEN-LAST:event_konversiDexliteButton21552011235ActionPerformed

    private void konversiPertamaxButton21552011235MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_konversiPertamaxButton21552011235MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_konversiPertamaxButton21552011235MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pomBensinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pomBensinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pomBensinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pomBensinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pomBensinGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dexliteLabel21552011235;
    private javax.swing.JTextField dexliteTextField21552011235;
    private javax.swing.JTextField inputTextField21552011235;
    private javax.swing.JLabel inputUang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton konversiDexliteButton21552011235;
    private javax.swing.JButton konversiPertaliteButton21552011235;
    private javax.swing.JButton konversiPertamaxButton21552011235;
    private javax.swing.JLabel pertaliteLabel21552011235;
    private javax.swing.JTextField pertaliteTextField21552011235;
    private javax.swing.JLabel pertamaxLabel21552011235;
    private javax.swing.JTextField pertamaxTextField21552011235;
    // End of variables declaration//GEN-END:variables
}
